import numpy

__author__ = 'Emanuele Tamponi'


class TermsError(Exception):
    pass


class CategoryInfo(object):

    def __init__(self, category, documents, terms, frequencies, children):
        self.category = category
        self.documents = documents
        self.terms = terms
        self.frequencies = frequencies
        self.children = children


class CategoryInfoBuilder(object):

    def __init__(self, terms):
        self.terms = numpy.asarray(sorted(terms))
        self.term_positions = {term: i for i, term in enumerate(self.terms)}

    def build_leaf(self, category, documents, term_frequencies):
        full_frequencies = numpy.zeros(len(self.terms))
        for term, frequency in term_frequencies.iteritems():
            full_frequencies[self.term_positions[term]] = frequency
        return CategoryInfo(category, documents, self.terms, full_frequencies, set())

    def build_node(self, children):
        if not isinstance(children, set):
            raise ValueError("Expecting set of CategoryInfo")
        if any(ci.terms is not self.terms for ci in children):
            raise TermsError("Cannot merge children not generated by me")
        categories = sorted(ci.category for ci in children)
        merged_category = "(" + "+".join(categories) + ")"
        merged_documents = sum(ci.documents for ci in children)
        merged_frequencies = sum(ci.frequencies for ci in children)
        return CategoryInfo(merged_category, merged_documents, self.terms, merged_frequencies, children)
